### ISSUE TITLE
authoryear

### ISSUE THREAD

**Issue by pierreganty** [jspitz/biblatex-publist#10]
I managed to get the bibliography into the form I needed with marginyear, highlighted author and nobold year but I do not manage to get the bibliography in the authoryear style.
No matter what I do it falls back onto the numeric style (my goal is to get rid of the [x] in front of each entry) .
I used without success different combinations of
`\newcommand*\publistbasestyle{authoryear}`, `bibstyle=publist`, `style=publist`.
I enclose part of the log file which contains the following lines:
```
…
Package biblatex Info: Trying to load citation style 'publist'...
Package biblatex Info: ... file 'publist.cbx' found.
 (/usr/local/texlive/2017basic/texmf-dist/tex/latex/biblatex-publist/publist.cbx
File: publist.cbx 2017/11/14 v.1.8 biblatex citation style (JSP)
Package biblatex Info: Trying to load citation style 'numeric'...
Package biblatex Info: ... file 'numeric.cbx' found.
 (/usr/local/texlive/2017basic/texmf-dist/tex/latex/biblatex/cbx/numeric.cbx
File: numeric.cbx 2017/12/19 v3.10 biblatex citation style (PK/JW/AB)
…
```

**Comment by jspitz** [comment]
Add something like this to the preamble:
```
\defbibenvironment{bibliography}
{\list
	{}
	{\setlength{\leftmargin}{\bibhang}%
		\setlength{\itemindent}{-\leftmargin}%
		\setlength{\itemsep}{\bibitemsep}%
		\setlength{\parsep}{\bibparsep}}}
{\endlist}
{\item}
```

**Comment by pierreganty** [comment]
That does it. Thank you. I let you close the issue.

**Comment by jspitz** [comment]
For convenience, I have added a new option `plnumbered` that can be used  to switch off numbering more easily. Will be in v. 1.9 (on its way to CTAN as we speak).
