### ISSUE TITLE
labeldate=false and marginyear=true won't go together

### ISSUE THREAD

**Issue by ypsilonkah** [jspitz/biblatex-publist#12]
Dear Jürgen,
the aforementioned options won't work together. The margin years are not printed. When `labeldate=true` is set margins are typesetted -- but also year labels (2000a, 2000b, etc.) in random manner.
Best Yannick

**Comment by jspitz** [comment]
Thanks, fixed. BTW the correct option in current biblatex is `labeldateparts`, not `labeldate` (which is no longer a boolean).
