### ISSUE TITLE
Plauthor by first initial only, or with wildcard

### ISSUE THREAD

**Issue by montdor** [jspitz/biblatex-publist#15]
A bit opposite to the other enhancement request on here, I was thinking of (and hoping for) a way to use just an initial, or some sort of wildcard, to highlight all of the occurrences of the author's name. 

The standard style causes two problems for me: 
1. I am cited at times by first initial, at times by first and middle initials, at times by full first name, and at times by first name with initials. 
2. I have published several works with family members, meaning that I cannot just highlight my last name without giving a value to the first name variable.

Thought on if this would be feasible? I tried using a wildcard after my first initial, but that didn't work, though it may be something easy to add on the backend.

**Comment by jspitz** [comment]
I have added an option `plauthorfirstinit`.

If this option is set to true, you can (and must) pass an initial letter for the first name.

Please test (from the repo) and report back.

**Comment by montdor** [comment]
Works perfectly!

**Comment by jspitz** [comment]
biblatex-publist 1.12 will be released this weekend.
