### ISSUE TITLE
publist produces entry “with and <second author>” when omiting first author

### ISSUE THREAD

**Issue by andrewufrank** [jspitz/biblatex-publist#18]
I produce a publist with the current version of publist (File: publist.bbx 2018/09/01 v.1.11) and get in entries where I am the first author "(with and XX)", but not when I am not the first author (second or later). 
[![the first entry is wrong, the second correct][1]][1]
Here is a MWE:

    \documentclass{article}
    
    \usepackage[bibstyle=publist]{biblatex}
    
    \plauthorname{Frank}
    \begin{filecontents}{mwebib.bib}
    	
    @Article{Frank1994e,
    	author  = {Frank, Andrew U. and Timpf, Sabine},
    	title   = {Multiple Representations for Cartographic Objects in a Multi-Scale Tree - An Intelligent Graphical Zoom},
    	journal = {Computers and Graphics Special Issue on Modelling and Visualization of Spatial Data in GIS},
    	year    = {1994},
    	volume  = {18},
    	number  = {6},
    	pages   = {823--829},
    }
    	
    @Article{Buyong1991,
    	author  = {Buyong, Taher and Kuhn, Werner and Frank, Andrew U.},
    	title   = {A Conceptual Model of Measurement-Based Multipurpose Cadastral Systems},
    	journal = {Journal of the Urban and Regional Information Systems Association (URISA)},
    	year    = {1991},
    	volume  = {3},
    	number  = {2},
    	pages   = {35--49},
    }
    	}
    \end{filecontents}

    \begin{document}
    
    \title{XX publications}
    \author{}
    \date{\today}
    \maketitle
    
    
    \section{Articles}
    \newrefsection[mwebib]
    \nocite{*}
    \printbibliography[heading=none]  
    
    
    \end{document}

  [1]: https://i.stack.imgur.com/KXbmX.png

i have asked on stackoverflow and others can reproduce the error and suggested it is a small bug. Could you fix it to improve your very useful tool.
Thank you!

**Comment by gusbrs** [comment]
I had some trouble grasping the name formatting directives, but if I got things right, this might be of use: https://tex.stackexchange.com/a/461509/105447

**Comment by jspitz** [comment]
Thanks, all. Will be fixed in biblatex-publist 1.12 (to be released today).
