### ISSUE TITLE
Feature request: Bold author names

### ISSUE THREAD

**Issue by michaelaye** [jspitz/biblatex-publist#2]
Hi!
Thanks for your package!
In science, the publication lists often require (or at least as a nice-to-have) to bold-print your name in a multi-author publication, could this be added as an option to your package?
Like this:

Smith, John; **Baker, Alfred** ; Sonders, Sven ...

**Comment by jspitz** [comment]
Can you try out the version here in the repo? The new option `plauthorhandling=embolden` should do what you want.

**Comment by jspitz** [comment]
I have changed the syntax. Now the relevant option is called `plauthorhandling=highlight`.

**Comment by jspitz** [comment]
Implemented in v. 1.4, which will be released to CTAN today.

**Comment by michaelaye** [comment]
Thank you for the fast implementation! Sorry, I'm not so fluent with trying out GH versions with Latex. Would it have been possible simply to create a tex file in the same folder and then the `.bbx` file would have been used?

**Comment by jspitz** [comment]
Yes, copying the `.bbx` file in the working directory works. Anyway, you can now try out directly after a TexLive update.

**Comment by michaelaye** [comment]
yes, i did and it works fine, thank you again.
