### ISSUE TITLE
Compatibilty problem with "biblatex-enc" base style

### ISSUE THREAD

**Issue by leodumont** [jspitz/biblatex-publist#21]
Hello,

First of all thanks for your work! I'm trying to use biblatex-publist with an external base style called [biblatex-enc](https://github.com/Jean-Baptiste-Camps/biblatex-enc) and if things go pretty smoothly, I encountered a problem related to the formatting of article entries.

In biblatex-enc there are [macros that print year field in parentheses](https://github.com/Jean-Baptiste-Camps/biblatex-enc/blob/dc9f13f95c4409588c45b422b9e353371e766e9a/enc.bbx#L174). When using that style with biblatex-publist the year field is displayed at the begining of the reference as expected, but the parentheses from biblatex-enc are left empty. Here is an exemple:

![Sélection_077](https://user-images.githubusercontent.com/908404/56654203-ce5bf400-668f-11e9-9df2-b38888422fb9.png)

Any hint on how to solve that issue? Thanks in advance

**Comment by jspitz** [comment]
I'd say you need to redefine the two respective macros from that style. Untested:
```
\renewbibmacro*{issue+date}{%
    \iffieldundef{issue}
      {\iffieldundef{month}
         {\printfield{year}}
         {\iffieldundef{day}
            {\printfield{month}%
             \setunit{\addspace}%
             \printfield{year}}
            {\printdate}}}
      {\printfield{issue}%
       \setunit{\addspace}}%< CHANGED!
  \newunit}

\renewbibmacro*{journal+issuetitle}{%
  \usebibmacro{journal}%
  \newunit%
  \iffieldundef{series}
    {}
    {\newunit%
     \printfield{series}%
     \setunit{\addspace}}%
  \printfield{volume}%
  \iffieldundef{number}{}{%
  \setunit{\textendash}%
  \printfield{number}}%
  \printfield{eid}%
  \addspace%
  \ifthenelse{\iffieldundef{issue}\AND\iffieldundef{month}\AND\iffieldundef{day}}{}{%
     \mkbibparens{\usebibmacro{issue+date}}%
  }%
  \newunit%
  \usebibmacro{issue}%
\newunit}
```

**Comment by leodumont** [comment]
Thanks for your proposition which does the trick!
