### ISSUE TITLE
Highlight Author in Short List

### ISSUE THREAD

**Issue by floydie7** [jspitz/biblatex-publist#23]
Hello, first of all, thank you for making this. I was bashing my head in with various biblatex hacks trying to come close to this.

I have a feature request:
Would it be possible to print the author list with the `plauthorname` highlighted but without having to display a very long author list? Essentially I'm looking for an output like this

First. Author, ... **My. Name**, et al. **July 2020** (Rest of citation details).

How many authors are displayed before the ellipses would be determined by the `maxnames` biblatex option as normal.

**Comment by jspitz** [comment]
I've implemented something at 2812a1b370ea. Please test.

This also properly truncates lists with `plauthorhandling=omit`. Note, though, that I only add "et al." if more names would follow the last highlighted name. And the omission is indicated by `[...]` (but this can be customized).

**Comment by floydie7** [comment]
That works perfectly, thanks!

**Comment by jspitz** [comment]
V. 1.18 has been submitted to CTAN.
