### ISSUE TITLE
\bpl@ifplauthor fails to recognise authors with initials before full given name(s)

### ISSUE THREAD

**Issue by moewew** [jspitz/biblatex-publist#24]
Inspired by https://tex.stackexchange.com/a/557647/35864

Consider
```latex
\documentclass{article}

\usepackage[backend=biber, style=publist, plauthorhandling=highlight]{biblatex}

\plauthorname[R. Giskard]{Reventlov}
\plauthorname[Humphrey]{Appleby}

\begin{filecontents}{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby and Bernard Woolley},
  title   = {On the Importance of the Civil Service},
  date    = {2019},
}
@article{reventlov,
  author  = {R. Giskard Reventlov and Someone Else},
  title   = {Turtles},
  date    = {2020},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```
which produces
> Reventlov, R. Giskard and Else, Someone. 2020. “Turtles”. In:
> **Appleby, Humphrey** and Woolley, Bernard. 2019. On the Importance of the Civil Service.

![image of the output: 'Reventlov, R. Giskard' is not highlighted, but 'Appleby, Humphrey' is.](https://user-images.githubusercontent.com/6755835/89710044-133c9480-d980-11ea-96ca-c167aff6b204.png)

Reventlov, R. Giskard is not highlighted as expected.

If I understand correctly the problem here is caused by the difference between the name formatting in `\indexnames` and `\printnames`. At the moment `\bpl@normalize` tries to ignore these differences by setting `\bibnamedelima` and `\bibnamedelimb` to their `\bibindexnamedelim...` equivalent.

https://github.com/jspitz/biblatex-publist/blob/09b60154497e3c66911d7e882844c8e7daca7352/publist.bbx#L226-L236

You should be able to get the same normalisation more elegantly and more comprehensively also for `\bibnamedelimi` (which is the problem here and possibly other relevant macros)  with `\blx@indexnamesetup` (https://github.com/plk/biblatex/blob/2ddd2836927d08ac600c8fa3af1897417548ac05/tex/latex/biblatex/biblatex.sty#L4592-L4600)

```latex
\def\bpl@normalize#1#2{%
    \begingroup
    \blx@indexnamesetup
    \def\IeC##1{##1}%
    \protected@edef\@tempa{#1}%
    \gdef\@gtempa{}%
    \expandafter\bpl@@normalize\@tempa\@nil
    \endgroup
    \let#2\@gtempa
}
```

**Comment by jspitz** [comment]
Thanks, I committed the fix.

**Comment by moewew** [comment]
Thanks you for the quick fix.
