### ISSUE TITLE
feature request: inverse numbering of entries

### ISSUE THREAD

**Issue by art-keidan** [jspitz/biblatex-publist#26]
Dear Author,
if I am allowed to request a feature, I would like to have an option of the inverse numbering of the publications, from the latest to the earliest. See an example here:
[https://tex.stackexchange.com/questions/563317/inverse-numbering-with-publist/](https://tex.stackexchange.com/questions/563317/inverse-numbering-with-publist/)

This option is useful when you have dozens of publications spreading on a few pages: you do not need to go all the way down in order to know the total amount of your publications.

**Comment by jspitz** [comment]
Sure, you're welcome to do so.

I have implemented the option `reversenumbering` for the next release (1.21, under development).

(it was a bit more complicated than the stackexchange solution suggested, keeping the numbering over mutliple refsections constant and also supporting `plnumbering=reset`)

**Comment by art-keidan** [comment]
Thank you so much.
