### ISSUE TITLE
Literal sub-numbering of unpublished items

### ISSUE THREAD

**Issue by art-keidan** [jspitz/biblatex-publist#27]
One more useful feature to implement would be the literal numbering of the unpublished items. For example, if there are two, or more, publications indicated as `Forthcoming`, they should be labeled as `Forthcoming a`,` Forthcoming b`, etc. As for now, all the forthcoming (or other unpublished) items repeat the same label with no differentiation, which is a bit redundant (see the example below).
![Schermata 2020-09-21 alle 21 28 44](https://user-images.githubusercontent.com/18039080/93812319-b2c49680-fc51-11ea-93fc-9349aa28dee0.png)

**Comment by jspitz** [comment]
Please try this:
```tex
% Add extra label also to pubstate, and prefer pubstate over year.
\renewbibmacro*{bpl:date:makedate}{%
  \printtext{%
     \iffieldundef{pubstate}{%
        \iffieldundef{year}{}{%
          \printfield{labelyear}%
          \printfield{extradate}%
        }%
      }{%
       \printfield{pubstate}%
       \printfield{extrayear}%
      }%
     }%
}
```

**Comment by art-keidan** [comment]
Thanks, it works.

**Comment by jspitz** [comment]
Next version (1.22) will have an option `pubstateextra` where you can switch this on.
