### ISSUE TITLE
Negative reference numbers

### ISSUE THREAD

**Issue by axel-loewe** [jspitz/biblatex-publist#28]
I get negative reference numbers when using `reversenumbering=true,plnumbered=reset` as can be seen from sections 1 and 3 in the working example attached.
It's built using `latexmk -pdf -shell-escape --output-directory=build publist`.
Any ideas how to address this issue?

[NegativeNumbers.zip](https://github.com/jspitz/biblatex-publist/files/5312168/NegativeNumbers.zip)

**Comment by jspitz** [comment]
The problem here is, AFAICS, that you have publications in your list of which your are not author. Use
```tex
\printbibliography[filter=mine,heading=none]
```
to filter out only your publications.

Reverse counting of other people's publications (such as the supervised theses) is not (yet) supported.

**Comment by axel-loewe** [comment]
Thank you for the swift response. This was indeed the reason.
