### ISSUE TITLE
Feature request: Title first option

### ISSUE THREAD

**Issue by abjer** [jspitz/biblatex-publist#29]
In some disciplines it is common to have titles first in the bibliography before writing "(with NN1, NN2), YYYY". I'd very much appreciate that way of organizing the publication list.

Example [here](https://tex.stackexchange.com/questions/297087/putting-the-title-first-in-the-bibliography) of how to do it in biblatex.

BTW. - I really love the package!

**Comment by jspitz** [comment]
I'd say this is not mainly a `publist` issue. The order is determined by the inherited base style (`authoryear.bbx` by default, that means: `standard.bbx`), in the bibliography drivers. E.g., for article, redefine the default like so
```tex
\DeclareBibliographyDriver{article}{%
	\usebibmacro{bibindex}%
	\usebibmacro{begentry}%
	\usebibmacro{title}% <--- MOVED
	\setunit{\addspace}% <--- ADDED
	\usebibmacro{author/translator+others}%
	\newblock
	\newunit
	\printlist{language}%
	\newunit\newblock
	\usebibmacro{byauthor}%
	\newunit\newblock
	\usebibmacro{bytranslator+others}%
	\newunit\newblock
	\printfield{version}%
	\newunit\newblock
	\usebibmacro{in:}%
	\usebibmacro{journal+issuetitle}%
	\newunit
	\usebibmacro{byeditor+others}%
	\newunit
	\usebibmacro{note+pages}%
	\newunit\newblock
	\iftoggle{bbx:isbn}
	{\printfield{issn}}
	{}%
	\newunit\newblock
	\usebibmacro{doi+eprint+url}%
	\newunit\newblock
	\usebibmacro{addendum+pubstate}%
	\setunit{\bibpagerefpunct}\newblock
	\usebibmacro{pageref}%
	\newunit\newblock
	\iftoggle{bbx:related}
	{\usebibmacro{related:init}%
		\usebibmacro{related}}
	{}%
	\usebibmacro{finentry}}
```

The only thing you need to redefine from publist is the order in the author macro, like this:
```tex
\renewbibmacro*{author}{%
    \ifnameundef{author}
        {}
        {%
            \usebibmacro{bpl:marginyear}%
            \printnames[][-\value{listtotal}]{author}%
            \setunit{\addspace}%
            \iffieldundef{nameaddon}
            {}
            {%
                \mkbibbrackets{%
                       \bibstring{alias}%
                        \addspace\printfield{nameaddon}%
                }%
            }%
    }%
    \addcomma\addspace%
    \usebibmacro{bpl:year+labelyear}%
}
```

Not much I can do in `publist` I'm afraid. I'd suggest you set up a respective base style and to the author macro modification in the preamble of the document.

**Comment by abjer** [comment]
That's great, thanks for the advice!

**Comment by dkwo** [comment]
This is definitely possible, but perhaps it's desirable that such style is implemented in biblatex-publist (after all the purpose is to produce a publication list). Otherwise one has to redefine in similar way the driver for online, then phdthesis, and so on. Btw, if I don't do anything, my phd thesis starts with a comma: `, year. “Title”. PhD thesis. School, City.`
