### ISSUE TITLE
I get the word 'AND' appearing twice 

### ISSUE THREAD

**Issue by rcatwood** [jspitz/biblatex-publist#3]
In the author list from biblatex publist as installed today in MikTex, the result shows the word 'and' appearing twice in each reference with more than two authors. 
This is not the desired output. 

The input file is not too complicated, and the bibliiography is just generated from WoK download. If I use ordinary Bibtex it doesn't do that (but doesn;t also do some extra features that publist provides! ) 
For example: (boldface added by me) 

Cai, B. Wang, J. Kao, A. Pericleous, K. Phillion, A. B. **And** Atwood,
R. C. **And** Lee, P. D. 2016. “4D synchrotron X-ray tomographic quantifi-
cation of the transition from cellular to dendrite growth during directional
solidification”. In: ACTA MATERIALIA 117, 160–169. issn: 1359-6454.
doi: {10.1016/j.actamat.2016.07.002}.
Files attached  that I used to get this output:

[fixbltx.pdf](https://github.com/jspitz/biblatex-publist/files/804672/fixbltx.pdf)

zipped here: 

[mypubs.zip](https://github.com/jspitz/biblatex-publist/files/804681/mypubs.zip)

Thank you

**Comment by jspitz** [comment]
Thanks, this was a bug. Can you test the recent version of publist.bbx from the github repository?

**Comment by jspitz** [comment]
BTW for proper output (non-capital "and" and correct commas between all auhor names) you have to use
```
backend=biber,
firstinits=true,
```

**Comment by rcatwood** [comment]
The new publist.bbx works for the extra 'and' ; Thanks! 

However , the capital 'And' and the incorrect commas do not depend upon the backend  (biber,bibtex) in my tests. They depend upon the 'firstinits'. Do you not consider this a bug too? If I use 'firstinits=true' I get almost what I wanted but the default (and 'firstinits=false' ) seems incorrect still? 

I hate to point out .. the justification gets wrong (extra space on first line)  with plauthorhandling=highlight also, while there is not an extra space in the default

**Comment by jspitz** [comment]
```
However , the capital 'And' and the incorrect commas do not depend upon the
backend (biber,bibtex) in my tests. They depend upon the 'firstinits'.
```
Not here. This is with recent biblatex. The only difference with `firstinits=false` is that I get no abbreviation dot after the initials (which is expected).

**Comment by jspitz** [comment]
> I hate to point out .. the justification gets wrong (extra space on first line) with
 plauthorhandling=highlight also, while there is not an extra space in the default

This is fixed now. Please verify.

**Comment by rcatwood** [comment]
Yes , it works for me too .  The first line text is now justified with the rest of the paragraph. Thanks again.

**Comment by rcatwood** [comment]
Regarding the other behavior , the log file claims for Biblatex:

(.... AppData\Roaming\MiKTeX\2.9\tex\latex\biblatex\biblatex.sty
Package: biblatex 2016/12/05 v3.7 programmable bibliographies (PK/JW/AB)

But if it works for you and it's some nested  package issue , i won't worry about it and just wait for MikTeX to catch up
