### ISSUE TITLE
Bibtex default styles and year of publication

### ISSUE THREAD

**Issue by DominikGlodzik** [jspitz/biblatex-publist#31]
Hello there,

thank you for putting together these highly useful tools!

I am using biblatex-publist on top of the 'nejm' bibliography style. 

I would like publication dates to be displayed is in the default 'nejm' style, that is, towards the end of the line.
![image](https://user-images.githubusercontent.com/23527069/120863861-53958080-c559-11eb-92a9-6f09340e49ac.png)

With biblatex-publist, I get something like this:
Fiala, EM, Ortiz, MV, Kennedy, JA, Glodzik, D, Fleischut, MH, Duffy, KA, et al. 2020. 11p15. 5 epimutations in children with Wilms tumor and hepatoblastoma detected in peripheral blood. Cancer. 126:3114–21.

With biblatex-publist, Is there a way to move the publication year towards the end of the line, in accordance with the baseline bibliography style?

Best & thank you
Dominik

Here are some relevant lines from my .tex file:
`\newcommand*\publistbasestyle{nejm}
\usepackage[style=publist,plauthorhandling=highlight,boldyear=false,pubstateextra=false,plauthorfirstinit=true,
minnames=6,marginyear=true]{biblatex}
`

**Comment by jspitz** [comment]
Add
```
\renewbibmacro*{bpl:year+labelyear}{}
```
below the lines you posted.

**Comment by DominikGlodzik** [comment]
Thank you very much for your response! Moving the publication year worked. 

![Screen Shot 2021-06-10 at 1 19 46 PM](https://user-images.githubusercontent.com/23527069/121569253-95f20e00-c9ee-11eb-9e9a-5cf5d09eaa41.png)

Is it possible to remove the comma after the last name, match the vanilla 'nejm' style?

In ideal world, I would like to replicate the Vancouver style:

![Screen Shot 2021-06-10 at 1 26 51 PM](https://user-images.githubusercontent.com/23527069/121570126-9212bb80-c9ef-11eb-9f36-471052c176a6.png)

I read around, and there is apparently no vancouver style for biblatex. Would you have any pointers to make the entries look more like vancouver?

Thank you for your time!
Dominik

**Comment by jspitz** [comment]
Add this below the definitions already done to remove the comma:

```tex
\usepackage{xpatch}
\xpatchbibmacro{bpl:handlenames}{\addcomma\addspace\namepartgiveni}{\addspace\namepartgiveni}{}{}
\xpatchbibmacro{bpl:handlenames}{\addcomma\addspace\namepartgiveni}{\addspace\namepartgiveni}{}{}
```

The doubling of `\xpatchbibmacro` is intentional.

**Comment by jspitz** [comment]
BTW I submitted a change at 7bf1a5f3f514 which will make it a bit easier and which will do the right thing for the commas with `nejm` right away

**Comment by DominikGlodzik** [comment]
Thank you very much! This is indeed working as expected - comma removed. 

If you had any ideas/pointers about the vancouver style, please let me know.

Best wishes.

**Comment by jspitz** [comment]
There is this one, but according to the comments, it seems to have some flaws:
https://ctan.org/pkg/biblatex-vancouver
Maybe useful as a base nonetheless?
