### ISSUE TITLE
Different options in different refsections

### ISSUE THREAD

**Issue by physkets** [jspitz/biblatex-publist#33]
Is it possible to modify the package so that each `\newrefsection[]` has its own options?

Say I want the author names highlighted in a list of publications, but hidden in a list of conferences.

It would also be nice if it were possible to switch base-styles, but that might not be easy.

**Comment by jspitz** [comment]
You can do that by changing internal booleans. E.g., putting
```tex
\makeatletter
\@hlauthortrue
\makeatother
```
will highlight the author name from that point on. Reversely, 
```tex
\makeatletter
\@hlauthorfalse
\makeatother
```
will switch off highlighting.

It would be good to have a more convenient interface. Alas, `biblatex`'s `\ExecuteBibliographyOptions` is only allowed in preamble, and there is also no other way to switch `biblatex` options in the body AFAICS.

IIRC switching styles underway is not supported by `biblatex`.

**Comment by physkets** [comment]
Ah, I see.. so its a fundamental limitation. Would've been nice though.

I've temporarily sloved the specific issue I described, by using the `@proceedings` entry type which does not display authors in the `phys` style that I have set.

**Comment by jspitz** [comment]
For the next version, I have changed the underlying option handler from `biblatex`'s own `BibliographyOptions` to `l3keys` and implemented a command `\ExecutePublistOptions` that will match this request for almost all options.
