### ISSUE TITLE
Issue with related fields

### ISSUE THREAD

**Issue by ienissei** [jspitz/biblatex-publist#34]
I encountered an issue when using related fields in a resume. The plauthor name would show in the entries which followed an entry with a related field. I solved the issue by changing the code as follows (line before last from `\toggletrue` to `\togglefalse`):

```
% This is to prevent author omission in such cases.
\newtoggle{isinrelated}
\apptocmd{\abx@macro@begrelated}{\global\toggletrue{isinrelated}}{}%
         {\PackageWarning{biblatex-publist}{Patching begrelated failed!}}
\apptocmd{\abx@macro@endrelated}{\global\togglefalse{isinrelated}}{}%
         {\PackageWarning{biblatex-publist}{Patching endrelated failed!}}
```

I am unsure whether this is a bug in `publist` or an incompatibility with my own bibliography style or usage of the related field (in this case, for putting two items on the same line/block). In any event, feedback would be appreciated.

**Comment by jspitz** [comment]
Thanks, definitely a typo. Fixed for the next release.
