### ISSUE TITLE
Conflict with linktitle and MakeSentenceCasing

### ISSUE THREAD

**Issue by hainingpan** [jspitz/biblatex-publist#37]
I am trying to change the base style to [phys](https://ctan.org/pkg/biblatex-phys?lang=en). However, there is an error message, which I don't know how to solve, `Package biblatex Error: Bibliography macro '\NoCaseChange {bpl:linked}' undefined.`

Is there anything I need to change to make it works? Thank you!

**Comment by jspitz** [comment]
It seems to work for me. MWE:
```tex
\documentclass{article}
\newcommand*\publistbasestyle{phys}
\usepackage[style=publist]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
	\textcite{doody}
	\printbibliography
\end{document}
```
![grafik](https://user-images.githubusercontent.com/4538783/167076719-1dc14aaf-6600-481e-b2a4-0779cbb07299.png)

Not that `\NoCaseChange` is a macro provided by `biblatex` itself, but you need a recent enough version of `biblatex` for that.

**Comment by hainingpan** [comment]
Thanks for your reply! I have checked my `biblatex` version, which is fine. I can also successfully compile your MWE. However, I find that it is because of `linktitleall=true` in the option of `biblatex` that gives the error message of `\NoCaseChange`.

Here is a MWE that can reproduce this error message.
```
% test.tex
\documentclass{article}
\newcommand*\publistbasestyle{phys}
\usepackage[style=publist,plauthorhandling=highlight,linktitleall=true]{biblatex}
\usepackage{amsmath,amssymb}
\plauthorname[Haining]{Pan}
\addbibresource{test.bib}
\begin{document}
\printbibliography[heading=none]
\nocite{*}

\end{document}
```

```
% test.bib
@article{pan2021interactiondriven,
  title = {Interaction-{{Driven Filling-Induced Metal-Insulator Transitions}} in {{2D Moir\'e Lattices}}},
  author = {Pan, Haining and Das Sarma, Sankar},
  year = {2021},
  month = aug,
  journal = {Phys. Rev. Lett.},
  volume = {127},
  number = {9},
  pages = {096802},
  publisher = {{American Physical Society}},
  doi = {10.1103/PhysRevLett.127.096802},
  copyright = {All rights reserved},
  day = 24
}
```
If I remove the option `linktitleall=true`, then the error goes away, which, however, also removes the link on the title undesirably.

**Comment by jspitz** [comment]
Yes, the linking trickery of publist does not work if sentence casing is enforced. Currently, all you can do is switch off sentence casing via
```tex
\DeclareFieldFormat{titlecase}{#1}
```

**Comment by jspitz** [comment]
Workaround:
```tex
% test.tex
\documentclass{article}
\usepackage{hyperref}
\newcommand*\publistbasestyle{phys}
\usepackage[style=publist,plauthorhandling=highlight,linktitleall=true]{biblatex}
%% WORKAROUND for https://github.com/jspitz/biblatex-publist/issues/37
\togglefalse{bpl@linktitle}
\DeclareFieldFormat{titlecase}{\usebibmacro{bpl:linked}{\MakeSentenceCase{#1}}}
%% END WORKAROUND
\usepackage{amsmath,amssymb}
\plauthorname[Haining]{Pan}
\addbibresource{37.bib}
\begin{document}
	\printbibliography[heading=none]
	\nocite{*}
	
\end{document}
```
