### ISSUE TITLE
Manually reset label numbers

### ISSUE THREAD

**Issue by laszabine** [jspitz/biblatex-publist#39]
Lieber Jürgen, 
My use case is that I would like to have two sets of continuously numbered refsections: one for publications, containing multiple refsections for different types of publications; and one for presentations, also containing multiple refsections. I'm looking for a way to achieve this using your package. (Thank you for this package!! I love it!) I think the easiest option would be to include a command that resets the label numbers at the right position in my document. I don't have any experience writing packages, so I'm struggling to figure out what that command should be. Could you please help me? 
Danke! 
Lg Sabine

**Comment by jspitz** [comment]
I've introduce a command `\setbplnum` for the next version. If you can, please download the development version of `biblatex-publist.bbx` and test.

**Comment by laszabine** [comment]
Fantastic, thank you so much!

**Comment by jspitz** [comment]
Leave open until this is released.

**Comment by jspitz** [comment]
For your information, the next release will also introduce an alternative approach, the `bplnumgroup` environment. As opposed to `\setbplnum`, this one also works with descending numbers. If `plnumbered=reset` is used, everything which is in such an environment will be numbered continuously. For your specific use case (with ascending numbers), `\setbplnum` is still a bit more convenient, just mentioning here for the case someone who has `reversenumbering` steps into the discussion.

Still need to test some of the new features, then I'll release it.

**Comment by jspitz** [comment]
FYI for the version to be released, I have renamed `\setbplnum` to `\setplnum` and `bplnumgroup` to `plnumgroup`. This is for consistency with other labels in the package.
