### ISSUE TITLE
Support author names in the order of "First Last" instead of "Last, First"

### ISSUE THREAD

**Issue by xuhdev** [jspitz/biblatex-publist#4]
When using the biblatex-publist style, it does not work any more to swap the order of the first and last names as shown [here](http://tex.stackexchange.com/a/151827):

```latex
\DeclareNameAlias{sortname}{last-first}
\DeclareNameAlias{default}{last-first}
```

This is probably a nice feature to have.

**Comment by jspitz** [comment]
The `last-first` terminology has been deprecated by biblatex in favor of `given` and `family`. Anyway, swapping name order in biblatex-publist is not that easy, since the name routine is quite complex (due to the omission/highlighting mechanism).

**Comment by jspitz** [comment]
Could you please test the development version here from github and check if the new option `nameorder=given-family` suits your needs?

**Comment by xuhdev** [comment]
@jspitz It works great! Thank you!

**Comment by jspitz** [comment]
Thanks for testing. I have just submitted v. 1.6. to CTAN.
