### ISSUE TITLE
Label numbers negative if using combination of \cite and  \nocite

### ISSUE THREAD

**Issue by Svendergrosse** [jspitz/biblatex-publist#40]
Lieber Jürgen,
if I use a combination of \cite and \nocite, the label of the first reference in \cite is set to 1. As a consequence other entries in the bibliography can have negative numbers. It would be desirable, if the labels and sorting are set by \nocite instead.

My MWE is below.

Thanks,
Sven

`\documentclass{article}

\usepackage[
		sorting=ydnt,%
		style=publist,%
		]{biblatex}
\plauthorname[John]{Doe}
\addbibresource{mymonographs.bib}

\begin{filecontents}{mymonographs.bib}
@book{key1,
  author = {Author, A. and Doe, John},
  year = {2001},
  title = {1st book},
  publisher = {Publisher},
}

@book{key2,
  author = {Doe, John},
  year = {2002},
  title = {2nd book},
  publisher = {Publisher},
}

@book{key3,
  author = { Doe, John and Author, A.},
  year = {2003},
  title = {3rd book},
  publisher = {Publisher},
}

\end{filecontents}

\begin{document}
	\title{John Doe’s publications}
	\date{\today}
	\maketitle
	\section{Monographs}
	\newrefsection[mymonographs]
	 My first book is my favourite \cite{key1}.
	\nocite{*}
	\printbibliography[heading=none]
\end{document}
`

**Comment by jspitz** [comment]
Please use `\citeitem` rather than `\cite`, as advised in the manual.
