### ISSUE TITLE
Author annotations with publist

### ISSUE THREAD

**Issue by kaarthiksundar** [jspitz/biblatex-publist#41]
How does one go about getting author annotations work with publist. Apart from `plauthor`, I have other author annotations in the biblatex file like ``author+an = {1:student}``. When doing ``\renewcommand*{\mkbibnamefamily}[1]{\ifitemannotation{student}{#1*}{#1}}``, publist sort of overrides this. How do turn off this overriding.

**Comment by jspitz** [comment]
This is something I haven't accounted for yet.
Please try the development version of publist.bbx:
https://github.com/jspitz/biblatex-publist/raw/master/publist.bbx

**Comment by kaarthiksundar** [comment]
@jspitz Thanks for the quick response. This commit resolves that problem.
