### ISSUE TITLE
Can't get reversenumbering behavior since the last major release

### ISSUE THREAD

**Issue by k4rtik** [jspitz/biblatex-publist#42]
Hi, I noticed the package deprecated that option recently, but I tried both the new solution and reverting back to the previous `reversenumbering` option, but in both cases I am only seeing negative numbers instead of the desired output of global reverse count of papers.

**Comment by jspitz** [comment]
Maybe you are missing some LaTeX runs (see log file)? Reversenumbering requires several cycles to get the numbering right.

**Comment by art-keidan** [comment]
Dear @jspitz, the `reversenumbering` option is not working in my case either: the numbering starts from the negative value corresponding to the total of papers with the minus sign, and then goes down. I've made several runs after deleting all the generated files, but still no result. I attach a screenshot.
![screenshot](https://user-images.githubusercontent.com/18039080/205262923-3675f23e-ec6f-4a24-b020-dcbaee89b6b3.png)

**Comment by jspitz** [comment]
Please provide an example file.

**Comment by art-keidan** [comment]
Here it comes.
[example.zip](https://github.com/jspitz/biblatex-publist/files/10139935/example.zip)

**Comment by jspitz** [comment]
Thanks. Can you try with biblatex.bbx from here?
 https://github.com/jspitz/biblatex-publist/raw/master/publist.bbx

**Comment by k4rtik** [comment]
@jspitz I just tested with `reversenumbering` and it seems to work fine.

What's the non-deprecated method to achieve the same behavior now, `plnumbering=global-descending`?

Also, I was trying to play with `plnumbering=local-descending` but with that I see the numbering going from [5] to [-10] for a section like this:
```
\section{Publications}
\nocite{*}
\subsection{Refereed Conference Papers}
\printbibliography[heading=none,type=inproceedings,notkeyword={workshop},notkeyword={poster}]
\subsection{Refereed Workshop Papers}
\printbibliography[heading=none,type=inproceedings,keyword={workshop}]
\subsection{Theses \& Reports}
\printbibliography[heading=none,type=thesis]
\subsection{Preprints}
\printbibliography[heading=none,type=unpublished,notkeyword={poster}]
\subsection{Posters}
\printbibliography[heading=none,keyword={poster}]
```

**Comment by art-keidan** [comment]
@jspitz the new version works as expected, thank you!

**Comment by jspitz** [comment]
> What's the non-deprecated method to achieve the same behavior now, `plnumbering=global-descending`?

Yes. And `local-descending` if you want to have numbers reset at each bibsection (i.e., `reversenumbering, plnumbered=reset` previously).

**Comment by jspitz** [comment]
> Also, I was trying to play with `plnumbering=local-descending` but with that I see the numbering going from [5] to [-10] for a section like this:

Please always provide full (minimal) working examples, so that I can try to reproduce the behavior.

**Comment by jspitz** [comment]
BTW for multiple `\printbibliography`'s as in this example, you should really use refsections as advised in the `publist` manual.

**Comment by jspitz** [comment]
OK, I found that issue and fixed it. Note, however, that local numbering requires either `refsection` or `plnumgroup`. It does not reset at each `\printbibliography`.
