### ISSUE TITLE
format for seminars and conference talks

### ISSUE THREAD

**Issue by dkwo** [jspitz/biblatex-publist#43]
Just a quick question: what's the recommended format for seminars and conference talks in the bib file?

What I'd like it to print:
for seminar: name of university/dept, full date
for conf talk: name of conference/workshop, full date

Thanks!

**Comment by jspitz** [comment]
Probably `misc` or `unpublished`, which are both quite flexible. For the full date, `publist` provides extra sorting schemes that probably sort by month and day.

If you want to get more fancy, you can define your own `@talk` type with specific information.
