### ISSUE TITLE
How can I put the year field at the end?

### ISSUE THREAD

**Issue by aywi** [jspitz/biblatex-publist#45]
Hi, great package! Here is a problem. I prefer to use the bib styles that put the `year` field at the end (but before eprints), such as `ieee` and `trad-unsrt`. When I try to use `\newcommand*\publistbasestyle{<stylename>}` to change the base style, it looks like publist just ignores the order setting for the `year` field and still puts it right after the `author`. Is this hard-coded? Are there any simple methods to make it follow the setting of the base style? Thanks!

I am using the following settings:

```tex
\newcommand*\publistbasestyle{trad-unsrt}
\usepackage[bibstyle=publist,hlyear=false,nameorder=given-family,plauthorhandling=highlight,plsorting=ddnt]{biblatex}
```

**Comment by jspitz** [comment]
Yes, it's hardcoded.

Adding
```tex
\renewbibmacro*{bpl:year+labelyear}{}
```
below the lines you posted should solve it.

**Comment by aywi** [comment]
> Yes, it's hardcoded.
> 
> Adding
> 
> ```
> \renewbibmacro*{bpl:year+labelyear}{}
> ```
> 
> below the lines you posted should solve it.

Thank you! It works.

You might consider adding it to Section 3.2 "Using a Different Base Style" of the package documentation.

**Comment by jspitz** [comment]
I am considering an option, as this has been now requested repeatedly.

**Comment by aywi** [comment]
@jspitz Another problem: it may add an extra period at the end of the author list if the style's delimiter between author and title is not a period (e.g. comma for `ieee`). Any thoughts?

MWE:

```tex
\documentclass{article}

\newcommand*\publistbasestyle{ieee}
\usepackage[bibstyle=publist,hlyear=false,nameorder=given-family,plauthorhandling=highlight]{biblatex}
\renewbibmacro*{bpl:year+labelyear}{}
% \usepackage[bibstyle=ieee]{biblatex} % Use this setting to print the expected behavior
\addbibresource{biblatex-examples.bib}

\begin{document}

\nocite{herrmann,kastenholz,murray}
\defbibenvironment{Publications}
{\begin{enumerate}}
{\end{enumerate}}
{\item}
\printbibliography[env=Publications,heading=none]

\end{document}
```

**Comment by jspitz** [comment]
I have added a new option, `fixyear.` Setting `fixyear=false` should do what you want, also the punctuation should be correct now.

Please try and report back.

**Comment by aywi** [comment]
> I have added a new option, `fixyear.` Setting `fixyear=false` should do what you want, also the punctuation should be correct now.
> 
> Please try and report back.

Thanks! Now the outputs are identical.

MWE:

```tex
\documentclass{article}

\newcommand*\publistbasestyle{ieee}
\usepackage[bibstyle=publist,fixyear=false,nameorder=given-family,plauthorhandling=highlight]{biblatex}
% \usepackage[bibstyle=ieee]{biblatex} % Use this setting to print the expected behavior
\addbibresource{biblatex-examples.bib}

\begin{document}

\nocite{herrmann,kastenholz,murray}
\defbibenvironment{Publications}
{\begin{enumerate}}
{\end{enumerate}}
{\item}
\printbibliography[env=Publications,heading=none]

\end{document}
```

**Comment by jspitz** [comment]
V. 2.4 has been submitted to CTAN.
