### ISSUE TITLE
Negative numbers

### ISSUE THREAD

**Issue by jopetty** [jspitz/biblatex-publist#49]
The following minimal example results in a partial bibliography with non-positive reference labels for the first section:

<img width="1128" alt="Screenshot 2023-10-06 at 11 25 43 PM" src="https://github.com/jspitz/biblatex-publist/assets/8475789/4db7eecf-fada-4f1f-862d-91db7278137d">

I'm using only the default settings with `biblatex-publist` (e.g., no special sorting or anything):

```tex
% main.tex
\documentclass{article}

\usepackage[style=publist]{biblatex}
\addbibresource{publications.bib}

\nocite{*}

\begin{document}

\section{Journal Articles}
\printbibliography[heading=none, type=article]

\section{Conference Proceedings}
\printbibliography[heading=none, type=inproceedings]

\end{document}
```

```bib
% references.bib
@INPROCEEDINGS{conf-a,
  title = {Conference Paper A},
  author = {Appleseed, Johnny},
  booktitle = {Proc. A},
  date = {2023-07}
}

@INPROCEEDINGS{conf-b,
  title = {Conference Paper B},
  author = {Appleseed, Johnny},
  booktitle = {Proc. B},
  date = {2022-02}
}

@ARTICLE{journ-1,
  title = {Journal Paper 1},
  author = {Appleseed, Johnny},
  journaltitle = {Journal 1},
  date = {2021-12}
}

@ARTICLE{journ-2,
  title = {Journal Paper 2},
  author = {Appleseed, Johnny},
  journaltitle = {Journal 2},
  date = {2021-10}
}

@ARTICLE{journ-3,
  title = {Journal Paper 3},
  author = {Appleseed, Johnny},
  journaltitle = {Journal 3},
  date = {2023-03}
}

@INPROCEEDINGS{conf-c,
  title = {Conference Paper C},
  author = {Appleseed, Johnny},
  booktitle = {Proc. C},
  date = {2020-12}
}
```

Code to reproduce is attached as a zip file: [neg-num-publist.zip](https://github.com/jspitz/biblatex-publist/files/12836702/neg-num-publist.zip)

**BibLaTeX Version:** `3.19`
**biblatex-publist Version:** `V. 2.6 (2023-07-01)`
**Biber Version:** `2.19`

**Comment by jspitz** [comment]
Fixed for the next version. As a workaround, you can add
`\boolfalse{newsection}`
immediately under
`\usepackage[style=publist]{biblatex}`
