### ISSUE TITLE
ordering options

### ISSUE THREAD

**Issue by art-keidan** [jspitz/biblatex-publist#51]
Imagine I have multiple papers published within the same year. They are obviously labeled by adding letters to the year: 2024a, 2024b etc. Is there any way to decide which one comes as "a", which one as "b" etc.? This may become meaningful in case publications are somehow related to each other. For example I may have published two contributions in the same volume, plus some other papers: I want the two papers within the same volume to be listed continuously (e.g. 2024a and 2024b), rather than being separated by other random publications (e.g. 2024a, …something else, … 2024d). In my experience, biber orders same year publications in a totally random and unpredictable order.
Is this even feasible? 
Thank you in advance
Artemij

EDIT: I apologize for posting it here rather than in the requests section.

**Comment by jspitz** [comment]
It's not random.

As explained in the manual (sec. 8), `biblatex` and `biblatex-publist` sort the entries by so-called sorting templates. In `biblatex-publist`, this is by default `ydt` (= year, descending > title). You can change the template via the `sorting` option.

If you want to override the sorting scheme for individual entries only, please refer to the biblatex manual, sec. 3.6, for possible ways to do this (the diverse `sort*` field types).

Anyways, not a bug of this package.
