### ISSUE TITLE
Suggestion: number of citations as additional entry info

### ISSUE THREAD

**Issue by nplatis** [jspitz/biblatex-publist#53]
I would suggest adding one more specific entry-related field: the number of citations of the entry (i.e. the number of publications that cite the entry).

Thanks for this excellent package!

**Comment by jspitz** [comment]
Thanks for the suggestion, makes perfect sense.

I've added support for that at b7f910f41db964faf. There's a new option `citinfo` and a field `citations`; it works analogous to the other extra information.

I'd appreciate testing and feedback before I release, as this sort of information is not common in my own field. You'd need at least the `*.bbx`, `*.ldf` and `*.dbx` files from the repo to test this.

**Comment by nplatis** [comment]
Thank you for the immediate reaction!

When `citations` is used together with the `peerreview` key, it seems that a separator is missing. The result I am getting is
```[Single blind peer rev.cit.: 10; OA (green); JIF: 5]```
and
``` [Single blind peer reviewcitations: 10; OpenAccess (green); impact factor: 5].```

**Comment by jspitz** [comment]
Should be fixed with c9cd2241cec1. Please check, thanks.

**Comment by nplatis** [comment]
Looks fine now, I tested as many combinations of extra fields as I could.
