### ISSUE TITLE
Letter after year

### ISSUE THREAD

**Issue by austinj** [jspitz/biblatex-publist#57]
Hi, thanks for the excellent package. Is there a way to suppress the letter after the year when there are multiple entries published in the same year? For instance: going from `Lastname, Firstname M. (2022b). Article name, etc. `to `Lastname, Firstname M. (2022). Article name, etc.` when there are multiple entries from 2022.

**Comment by jspitz** [comment]
No option or somesuch. You'd need the following redefinition:
```tex
\renewbibmacro*{bpl:date:makedate}{%
    \printtext{%
        \iffieldundef{year}{%
            \iffieldundef{pubstate}%
                {}
                {\printfield{pubstate}}%
          }{\printdate}%
    }%
}
```

**Comment by austinj** [comment]
Thank you very much. For anyone looking for this in the future, I'm using APA style with `\newcommand*\publistbasestyle{apa}`, so I also had to modify the apa.bbx file to remove letters after years.  Those changes to apa.bbx are:

The code below

`\newbibmacro*{labelyear+extradate}{%
  \iffieldundef{labelyear}
    {\iffieldundef{origyear}
      {}
      {\printtext[apadate]{\printorigdate}}}%
    {\printtext[apadate]{\printlabeldateextra}}}`

Changes to

`\newbibmacro*{labelyear+extradate}{%
  \iffieldundef{labelyear}
    {\iffieldundef{origyear}
      {}
      {\printtext[apadate]{\printorigdate}}}%
    {\printtext[apadate]{\printlabeldate}}}
`

And these two lines are deleted

`uniquelist=minyear,%
uniquename=init,%
`
