### ISSUE TITLE
publist and backend=bibtex

### ISSUE THREAD

**Issue by ChristophHanck** [jspitz/biblatex-publist#6]
Hello, 

I cannot get publist and backend=bibtex to work together, as in 

\documentclass{article}

%\usepackage[bibstyle=publist,backend=bibtex,style=authoryear]{biblatex}
%\plauthorname{Hanck} % gives undefined control sequence

\usepackage[backend=bibtex,style=authoryear]{biblatex} % works as mwe, but without publist

\begin{filecontents}{jobname.bib}
@ARTICLE{Demetrescu+Hanck-CauchyCoint:17+,
  author       = {Matei Demetrescu and Christoph Hanck},
  title        = {Multiple Testing for No Cointegration under Nonstationary Volatility},
  year         = {2017+},
  journal      = {Oxford Bulletin},
}
\end{filecontents}

\addbibresource{jobname.bib}

\begin{document}
\cite{Demetrescu+Hanck-CauchyCoint:17+}
\end{document}

Is that behavior to be expected? If so, are there any workarounds to get publist to cooperate with backend=bibtex? 

Best wishes
Christoph

P.S. Nice to see an add-on to biblatex, a long time ago you helped me with an early hack, see https://groups.google.com/forum/#!topic/comp.text.tex/cI3Y-tTV7j4

**Comment by jspitz** [comment]
I am sorry, `biblatex-publist` depends on features that are only available with `biber`. This is also mentioned in the manual.

**Comment by ChristophHanck** [comment]
OK, thanks, I'll take this as an incentive to finally migrate!
