### ISSUE TITLE
Upcoming release of biblatex 3.8

### ISSUE THREAD

**Issue by moewew** [jspitz/biblatex-publist#7]
Version 3.8 of `biblatex` is scheduled for release quite soon.

As far as I can see none of the breaking changes should affect your package, but there are a few name changes/deprecations planned that are relevant for you:

- `extrayear` is deprecated now and replaced by `extradate`, all macros with `extrayear` in their name were also renamed.
- `\DeclareSortingScheme` is now `\DeclareSortingTemplate`

Backwards compatibility code is in place for both of these changes, but it would still be appreciated if styles could move to the new names sooner rather than later.

The full list of changes can be found at https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org and https://github.com/plk/biblatex/wiki

**Comment by jspitz** [comment]
Thanks for the heads-up, @moewew

**Comment by jspitz** [comment]
Closed with fc2bb08dd03a9f6
