### ISSUE TITLE
Don't understand \newrefsection

### ISSUE THREAD

**Issue by sjkiss** [jspitz/biblatex-publist#9]
Hi there: this is a great package, but I don't understand the usage of \newrefsection? IN your examples, the arguments always match the filename of the correspondng bibliography file. 

```
\addbibresource{%
mymonographs.bib
}

\newrefsource[mymonographs]
```

What is the connection between the two? \newrefsource is not fully explained.

**Comment by sjkiss** [comment]
I figure it out!

**Comment by jspitz** [comment]
`\newrefsection` is a biblatex feature. It is explained in sec 3.7.4 of the biblatex manual.

**Comment by jspitz** [comment]
I have added a reference to the docs.
